import * as vscode from 'vscode';

/**
 * Message generated by a plugin
 */
export interface PluginMessage {
  userPrompt: string;
  includeContext: boolean;
  text?: string; // Optional text to append to the LLM reply
}

/**
 * Context passed to plugins when generating messages
 */
export interface PluginContext {
  editor: vscode.TextEditor;
  panel: vscode.WebviewPanel;
  lastEditedFiles: string[];
  chatHistory: any[];
  getRelativePath: (absPath: string) => string;
  getLinesAround: (doc: vscode.TextDocument, centerLine: number, radius: number) => { start: number; end: number; text: string };
}

/**
 * Base interface for all plugins
 */
export interface IPlugin {
  /**
   * Unique identifier for the plugin
   */
  readonly id: string;

  /**
   * Human-readable name of the plugin
   */
  readonly name: string;

  /**
   * Whether this plugin is currently enabled
   */
  isEnabled(config: vscode.WorkspaceConfiguration): boolean;

  /**
   * Whether this plugin should trigger in the current context
   * Used by the periodic trigger to filter out plugins that shouldn't run
   * Returns true by default if not implemented
   */
  shouldTrigger?(context: PluginContext): boolean;

  /**
   * Generate a message for the LLM based on current context
   * Returns null if the plugin cannot generate a message in the current state
   */
  generateMessage(context: PluginContext): Promise<PluginMessage | null>;

  /**
   * Called when the plugin should activate (e.g., register event listeners)
   */
  activate?(context: PluginContext): void;

  /**
   * Called when the plugin should deactivate
   */
  deactivate?(): void;
}
