name: Release Extension

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Package extension
        id: package
        run: |
          npm run package
          VSIX_PATH=$(find . -maxdepth 1 -name "*.vsix" -print -quit)
          if [ -z "$VSIX_PATH" ]; then
            echo "VSIX package not found" >&2
            exit 1
          fi
          echo "VSIX_PATH=$VSIX_PATH" >> "$GITHUB_ENV"
          echo "vsix-path=$VSIX_PATH" >> "$GITHUB_OUTPUT"

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix-package
          path: ${{ steps.package.outputs.vsix-path }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: ${{ steps.package.outputs.vsix-path }}
          generate_release_notes: true